-- AutoGyrus v1.0
-- Module 001: Foundation tables

CREATE TABLE IF NOT EXISTS ag_provider_master (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    provider_code VARCHAR(100) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    provider_category VARCHAR(100) NOT NULL,
    provider_subcategory VARCHAR(100) NULL,
    api_base_url VARCHAR(500) NULL,
    documentation_url VARCHAR(500) NULL,
    auth_type VARCHAR(50) NULL,
    import_mode VARCHAR(50) NULL,
    provider_priority INT UNSIGNED NOT NULL DEFAULT 100,
    version_major INT UNSIGNED NOT NULL DEFAULT 1,
    version_minor INT UNSIGNED NOT NULL DEFAULT 0,
    rate_limit_per_minute INT UNSIGNED NULL,
    rate_limit_per_day INT UNSIGNED NULL,
    supports_webhooks TINYINT(1) NOT NULL DEFAULT 0,
    supports_images TINYINT(1) NOT NULL DEFAULT 0,
    supports_vin TINYINT(1) NOT NULL DEFAULT 0,
    supports_history TINYINT(1) NOT NULL DEFAULT 0,
    supports_specifications TINYINT(1) NOT NULL DEFAULT 0,
    supports_reviews TINYINT(1) NOT NULL DEFAULT 0,
    supports_pricing TINYINT(1) NOT NULL DEFAULT 0,
    supports_inventory TINYINT(1) NOT NULL DEFAULT 0,
    supports_marketplace TINYINT(1) NOT NULL DEFAULT 0,
    supports_bulk_sync TINYINT(1) NOT NULL DEFAULT 0,
    supports_delta_sync TINYINT(1) NOT NULL DEFAULT 0,
    provider_metadata JSON NULL,
    metadata JSON NULL,
    future_reserved JSON NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_provider_master_uuid (uuid),
    UNIQUE KEY uq_ag_provider_master_provider_code (provider_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_country (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    iso2 VARCHAR(2) NOT NULL,
    iso3 VARCHAR(3) NULL,
    country_name VARCHAR(150) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_country_uuid (uuid),
    UNIQUE KEY uq_ag_country_iso2 (iso2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_state_province (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    country_id BIGINT UNSIGNED NULL,
    province_code VARCHAR(50) NOT NULL,
    province_name VARCHAR(150) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_state_province_uuid (uuid),
    UNIQUE KEY uq_ag_state_province_country_code (country_id, province_code),
    CONSTRAINT fk_ag_state_province_country
        FOREIGN KEY (country_id) REFERENCES ag_country(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_city (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    country_id BIGINT UNSIGNED NULL,
    province_id BIGINT UNSIGNED NULL,
    city_name VARCHAR(150) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_city_uuid (uuid),
    UNIQUE KEY uq_ag_city_scope (country_id, province_id, city_name),
    CONSTRAINT fk_ag_city_country
        FOREIGN KEY (country_id) REFERENCES ag_country(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_ag_city_province
        FOREIGN KEY (province_id) REFERENCES ag_state_province(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_manufacturer (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    manufacturer_name VARCHAR(150) NOT NULL,
    manufacturer_slug VARCHAR(180) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_manufacturer_uuid (uuid),
    UNIQUE KEY uq_ag_manufacturer_slug (manufacturer_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_body_style (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    body_style_name VARCHAR(150) NOT NULL,
    body_style_slug VARCHAR(180) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_body_style_uuid (uuid),
    UNIQUE KEY uq_ag_body_style_slug (body_style_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_engine_type (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    engine_type_name VARCHAR(150) NOT NULL,
    engine_type_slug VARCHAR(180) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_engine_type_uuid (uuid),
    UNIQUE KEY uq_ag_engine_type_slug (engine_type_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_transmission_type (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    transmission_type_name VARCHAR(150) NOT NULL,
    transmission_type_slug VARCHAR(180) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_transmission_type_uuid (uuid),
    UNIQUE KEY uq_ag_transmission_type_slug (transmission_type_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_drive_type (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    drive_type_name VARCHAR(150) NOT NULL,
    drive_type_slug VARCHAR(180) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_drive_type_uuid (uuid),
    UNIQUE KEY uq_ag_drive_type_slug (drive_type_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_fuel_type (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    fuel_type_name VARCHAR(150) NOT NULL,
    fuel_type_slug VARCHAR(180) NOT NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_fuel_type_uuid (uuid),
    UNIQUE KEY uq_ag_fuel_type_slug (fuel_type_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_currency (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    currency_name VARCHAR(100) NOT NULL,
    symbol VARCHAR(12) NULL,
    minor_unit TINYINT UNSIGNED NOT NULL DEFAULT 2,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_currency_uuid (uuid),
    UNIQUE KEY uq_ag_currency_code (currency_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_market (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    market_code VARCHAR(50) NOT NULL,
    market_name VARCHAR(150) NOT NULL,
    country_id BIGINT UNSIGNED NULL,
    currency_id BIGINT UNSIGNED NULL,
    language_code VARCHAR(10) NULL,
    region_code VARCHAR(50) NULL,
    market_type VARCHAR(50) NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_market_uuid (uuid),
    UNIQUE KEY uq_ag_market_code_country (market_code, country_id),
    CONSTRAINT fk_ag_market_country
        FOREIGN KEY (country_id) REFERENCES ag_country(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_ag_market_currency
        FOREIGN KEY (currency_id) REFERENCES ag_currency(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ag_system_lookup (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    lookup_group VARCHAR(100) NOT NULL,
    lookup_code VARCHAR(100) NOT NULL,
    lookup_name VARCHAR(255) NOT NULL,
    lookup_value VARCHAR(500) NULL,
    parent_lookup_id BIGINT UNSIGNED NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 100,
    metadata JSON NULL,
    future_reserved JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    change_reason VARCHAR(500) NULL,
    last_synced_at DATETIME NULL,
    last_provider_update DATETIME NULL,
    data_quality_score DECIMAL(5,2) NULL,
    confidence_score DECIMAL(5,2) NULL,
    source_system VARCHAR(100) NOT NULL DEFAULT 'autogyrus',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_ag_system_lookup_uuid (uuid),
    UNIQUE KEY uq_ag_system_lookup_group_code (lookup_group, lookup_code),
    CONSTRAINT fk_ag_system_lookup_parent
        FOREIGN KEY (parent_lookup_id) REFERENCES ag_system_lookup(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

