START TRANSACTION;
DELETE FROM wp_postmeta WHERE post_id = 79 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 79 AND post_title = '2026 Toyota bZ XLE Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota bZ XLE Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-79', '', '', NOW(), UTC_TIMESTAMP(), '', 79, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-79.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-79.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26BZ2706%2Fgoxtfc7llpdpkiea3cgd.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota bZ XLE');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (79, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (79, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 80 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 80 AND post_title = '2026 Toyota Tundra SR Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota Tundra SR Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-80', '', '', NOW(), UTC_TIMESTAMP(), '', 80, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-80.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-80.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26TU7453%2Fio5aknisrozzgzoc5s5n.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota Tundra SR');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (80, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (80, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 82 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 82 AND post_title = '2026 Toyota RAV4 XSE Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota RAV4 XSE Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-82', '', '', NOW(), UTC_TIMESTAMP(), '', 82, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-82.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-82.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26RH3630%2Fhjf8mktiokrmbaxl32og.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota RAV4 XSE');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (82, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (82, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 83 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 83 AND post_title = '2026 Toyota Tundra Limited Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota Tundra Limited Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-83', '', '', NOW(), UTC_TIMESTAMP(), '', 83, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-83.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-83.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26TU1379%2Fotz7cw5llgj1ie6fwg6p.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota Tundra Limited');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (83, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (83, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 85 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 85 AND post_title = '2026 Toyota Corolla Hybrid LE Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota Corolla Hybrid LE Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-85', '', '', NOW(), UTC_TIMESTAMP(), '', 85, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-85.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-85.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26CY6970%2Fvhmhmx8hqq9fjn0nvesw.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota Corolla Hybrid LE');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (85, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (85, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 86 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 86 AND post_title = '2024 Toyota Grand Highlander Hybrid Platinum Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2024 Toyota Grand Highlander Hybrid Platinum Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-86', '', '', NOW(), UTC_TIMESTAMP(), '', 86, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-86.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-86.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2FKS04020%2Fhvpxbxhfze7fymclchoi.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2024 Toyota Grand Highlander Hybrid Platinum');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (86, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (86, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 87 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 87 AND post_title = '2026 Toyota Tundra Platinum Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota Tundra Platinum Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-87', '', '', NOW(), UTC_TIMESTAMP(), '', 87, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-87.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-87.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26TU9817%2Flit995qclmgcalo35aec.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota Tundra Platinum');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (87, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (87, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 88 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 88 AND post_title = '2026 Toyota Corolla XSE Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota Corolla XSE Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-88', '', '', NOW(), UTC_TIMESTAMP(), '', 88, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-88.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-88.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26CO7168%2Fvlcyanhm2yigunnu02gk.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota Corolla XSE');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (88, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (88, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 89 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 89 AND post_title = '2025 Toyota Tundra Limited Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2025 Toyota Tundra Limited Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-89', '', '', NOW(), UTC_TIMESTAMP(), '', 89, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-89.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-89.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2FPC6526%2Fldxthnulhdj3go7t0lpa.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2025 Toyota Tundra Limited');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (89, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (89, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 90 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 90 AND post_title = '2026 Toyota RAV4 Plug-In Hybrid SE Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota RAV4 Plug-In Hybrid SE Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-90', '', '', NOW(), UTC_TIMESTAMP(), '', 90, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-90.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-90.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26RP6105%2Fzugyovvzddlq3ltjkfk8.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota RAV4 Plug-In Hybrid SE');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (90, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (90, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 93 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 93 AND post_title = '2020 Acura RDX Platinum Elite Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2020 Acura RDX Platinum Elite Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-93', '', '', NOW(), UTC_TIMESTAMP(), '', 93, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-93.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-93.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2FKS04927%2Fy7ogrzsl23j9rudwayk4.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2020 Acura RDX Platinum Elite');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (93, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (93, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 94 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 94 AND post_title = '2023 Mitsubishi Outlander ES Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2023 Mitsubishi Outlander ES Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-94', '', '', NOW(), UTC_TIMESTAMP(), '', 94, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-94.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-94.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2FKS12646%2Fgyt3pkazx06mxiyg4owi.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2023 Mitsubishi Outlander ES');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (94, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (94, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 95 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 95 AND post_title = '2021 Honda CR-V EX-L Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2021 Honda CR-V EX-L Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-95', '', '', NOW(), UTC_TIMESTAMP(), '', 95, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-95.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-95.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26CO9049A%2Fxnnlwujhjbbuui5zbib2.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2021 Honda CR-V EX-L');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (95, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (95, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 96 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 96 AND post_title = '2025 Honda Civic Si Sedan Manual Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2025 Honda Civic Si Sedan Manual Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-96', '', '', NOW(), UTC_TIMESTAMP(), '', 96, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-96.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-96.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2FAH80123%2Fne36poi8ja55yiupfgo7.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2025 Honda Civic Si Sedan Manual');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (96, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (96, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 97 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 97 AND post_title = '2021 Toyota 4Runner 4WD Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2021 Toyota 4Runner 4WD Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-97', '', '', NOW(), UTC_TIMESTAMP(), '', 97, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-97.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-97.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26TH5876A%2Fpg7uomnenjuyr18fsgfu.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2021 Toyota 4Runner 4WD');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (97, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (97, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 98 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 98 AND post_title = '2020 Toyota Highlander Hybrid Limited Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2020 Toyota Highlander Hybrid Limited Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-98', '', '', NOW(), UTC_TIMESTAMP(), '', 98, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-98.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-98.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26SH7338A%2Fyub7riowmkceqayy7cnj.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2020 Toyota Highlander Hybrid Limited');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (98, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (98, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
DELETE FROM wp_postmeta WHERE post_id = 99 AND meta_key IN ('_thumbnail_id', 'vehicle_primary_image');
DELETE FROM wp_posts WHERE post_type = 'attachment' AND post_parent = 99 AND post_title = '2026 Toyota Tundra Limited Featured Image'; 
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', '2026 Toyota Tundra Limited Featured Image', '', 'inherit', 'closed', 'closed', '', 'toyota-99', '', '', NOW(), UTC_TIMESTAMP(), '', 99, 'https://autogyrus.local/wp-content/uploads/2026/07/toyota-99.jpg', 0, 'attachment', 'image/jpeg', 0);
SET @attachment_id := LAST_INSERT_ID();
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attached_file', '2026/07/toyota-99.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_autogyrus_source_image_url', 'https://res.cloudinary.com/goauto-images/image/upload/f_auto,c_fill,w_640,ar_14:9,q_auto/v1/inventory%2Fdealer%2F52%2F26TU9716%2Fevbjhxo5tkeeqypicbm2.jpg');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (@attachment_id, '_wp_attachment_image_alt', '2026 Toyota Tundra Limited');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (99, '_thumbnail_id', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (99, 'vehicle_primary_image', @attachment_id) ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value);
COMMIT;
